
version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    command: mongod --port 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: p4$$w0rd

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "1015:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: p4$$w0rd
      # ME_CONFIG_MONGODB_URL: mongodb+srv://anspangilinan:3tKbHquI2x09dxsS@cluster0.i23uvdc.mongodb.net/?retryWrites=true&w=majority
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:p4$$w0rd@mongo:27017

  web:
    build:
      context: .
      target: deps
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      # MONGODB_URL: mongodb+srv://anspangilinan:b5OpBXnHxypkTeh2@cluster0.i23uvdc.mongodb.net/
      # MONGODB_URL: mongodb+srv://anspangilinan:3tKbHquI2x09dxsS@cluster0.i23uvdc.mongodb.net/?retryWrites=true&w=majority
      MONGODB_ENABLE_SSL: false
      MONGODB_URL: mongodb://rootuser:p4$$w0rd@mongo:27017
      MONGODB_NAME: inventory-iq-alpha
      NEXTAUTH_SECRET: N/9OuUGle2V7p6Jtx+qyPvw8K8b5oRKy0WhgKAocRn4=
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next